# Generated by Django 4.2.3 on 2023-10-01 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_sale_price_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 1, 17, 9, 53, 967447)),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=0, default=models.DecimalField(decimal_places=0, default=0, max_digits=12), max_digits=12),
        ),
    ]
